### PR TITLE
Updated to Mapping Table Salesforce

### PR DESCRIPTION
**Pull request by ritazagoni**

### CODE REVIEW

**Comment by lakhassane** [comment]
@ritazagoni could you walk me through what changes have been made here?
Those files have around 10 000 lines of json so I cannot possibly review them

**Review by lakhassane — CHANGES_REQUESTED** [review]
@ritazagoni I cannot merge it because you used the expanded json object rather that the minified. 
Please use the minified so we are sure only Line 3 is modified then we can approve it.

**Comment by ritazagoni** [comment]
@lakhassane sorry- apparently my formatter has overwritten the minified version, I had to undo that. It is indeed one line now-  let me know if it's okay!

**Comment by lakhassane** [comment]
@ritazagoni done! I removed the json files from the PR and just left `schedule_smsv2.js`

**Pull request merged**
